# quantum Makefile — the lifecycle only: help / build / test / lint / ci /
# publish / clean. Anything else is the `fluxor` CLI directly
# (`fluxor modules build`, `fluxor run`, `fluxor update`, `fluxor sync`,
# `fluxor build --check …`) — a make target that merely renames one CLI
# command is bloat, not convenience.
#
# The bodies are gate-enforced character for character by `fluxor ci`'s
# `makefile` phase (../standards/make.md §2). They are identical across
# projects because the VERB is not: each reads this checkout's shape — no root
# `Cargo.toml`, the three standalone host crates under `tools/`, `modules/` +
# `[ci].targets`, `[ci.test] scripts` — and does what that shape implies.
# `make help` is generated by `fluxor help --make`, which walks `tools/` for
# real, so the script list cannot fall behind the tree.
#
# Shadow-tracked `tests/` and `examples/` (../standards/test-tracking.md) are
# not targets either — `git shadow status` / `git shadow log` are one command
# each, and the staging incantation lives in README.md where a reader without
# the CLI installed can still find it.

SHELL       := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.DEFAULT_GOAL := build

.PHONY: help build test lint ci publish clean test-mqtt-suite

help:
	@fluxor help --make

build:
	fluxor build

test:
	fluxor test

lint:
	fluxor lint

ci:
	fluxor ci

publish:
	fluxor publish

clean:
	fluxor clean

# Not a lifecycle stage — a genuine composition (../standards/make.md §1.3),
# and §3 allows plain invocations in sequence, which is all this is. Every
# script below binds port 9090, so they must run strictly sequentially, and
# the graph boots from prebuilt PIC fmods, so the module build precedes them.
test-mqtt-suite:
	fluxor modules build --target bcm2712 --out target
	bash tests/integration/module_graph_mqtt.sh
	bash tests/integration/module_graph_pubsub.sh
	bash tests/integration/module_graph_resume.sh
	bash tests/integration/module_graph_mqtt_advanced.sh
	bash tests/integration/module_graph_will_delay.sh
	bash tests/integration/module_graph_load.sh
	bash tests/integration/module_graph_mqtt_quic.sh
	bash tests/integration/session_handoff.sh
	bash tests/integration/session_handoff_peer.sh
